services:
  web:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
    env_file: .env
    ports:
      - "8501:8501"
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
      - ./langgraph_components:/app/langgraph_components
      - ./credentials:/app/credentials
      # No montamos el directorio config para mantener los permisos del contenedor
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GOOGLE_CALENDAR_CREDENTIALS=${GOOGLE_CALENDAR_CREDENTIALS}